/**
 * Manejo de errores
 */

/*
// try ... catch

try {
    // codigo
}catch(err){
    //Manipulacion del error
}
*/

try {
    alert('Inicio del intento');

    // unaVarible;

    alert('Fin del intento');
}catch(error) {
    alert('Atencion ocurrio un error');
} finally {
    alert('Se ha ejecutado el codigo');
}